FROM busybox:latest

COPY email_templates /assets/email_templates
COPY engine /assets/engine
COPY KrameWork /assets/KrameWork
COPY modules /assets/modules
COPY templates /assets/templates
COPY www /assets/html