name: Build minecraft.runsafe.no

on:
  push:
    branches:
      - master
    paths:
      - "email-templates/**"
      - "engine/**"
      - "KrameWork/**"
      - "modules/**"
      - "templates/**"
      - "minecraft/**"
      - "Dockerfile.minecraft"
      - ".github/workflows/build-minecraft.yaml"

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/runsafe/web-minecraft

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.minecraft
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}